### ISSUE TITLE
add to faq

### ISSUE THREAD

**Issue by feuyeux** [graingert/slimerjs#11]
there's no description about running casperjs with slimerjs on nodejs:
SlimerJs can work as engine with casperjs on nodejs:
```javascript
spawn("casperjs", ['--engine=slimerjs', scriptFilePath, reportFileName, accessingUrl]);
```

**Comment by graingert** [comment]
Can you create a PR with this change in the docs please?

**Comment by graingert** [comment]
closing as I just want to track upstream Phantom.

@feuyeux if you want this change, add it to Phantom and I will merge it in here.
