### ISSUE TITLE
merge upstream phantomjs into slimerjs

### ISSUE THREAD

**Issue by graingert** [graingert/slimerjs#17]
We're missing some features like https://github.com/graingert/slimerjs/pull/16

It's probably best to pull them all in in one go.

**Comment by bushong1** [comment]
+1

**Comment by thhalm** [comment]
+1

**Comment by thhalm** [comment]
Any news on that? I would really appreciate some progress here... Thx in advance.

**Comment by graingert** [comment]
@thhalm no news, I'm waiting on a PR ;)

**Comment by thhalm** [comment]
Hello, I created the requested pull request 9 days ago. Any plans on accepting it in the next days?

**Comment by graingert** [comment]
@thhalm sorry I just didn't spot it till now!

**Comment by thhalm** [comment]
Ok, no problem. But I have also another wish ;-) Will be there a new npm release soon?
