### ISSUE TITLE
could you provide 0.10pre too?

### ISSUE THREAD

**Issue by burningTyger** [graingert/slimerjs#21]
I need pdf printing which is only available from 0.10 on. Could you provide a prerelease version, too?

**Comment by graingert** [comment]
@bitjson has an edge version of slimerjs you could try that?

**Comment by bitjson** [comment]
`npm install slimerjs-edge` should do it. :+1:

**Comment by graingert** [comment]
Btw @bitjson I invited you to become a contributor to this project, it would be good to release 0.10pre and 0.9.6 from the same codebase

**Comment by bitjson** [comment]
Oh, great, thanks! I can take a look at that in the next few days.



Jason

**Comment by burningTyger** [comment]
Sorry, completely forgot about this issue, have been using the .10 version available via the website for quite some time and it works well (with the version change to the application.ini file and cups installed). Please do add a note to the docs that cups is absolutely necessary to print to pdf. Thanks.

**Comment by burningTyger** [comment]
oh, this is the npm package. Should have checked where I post :)
