### ISSUE TITLE
install.js - Support overriding the download url to install from a local repository

### ISSUE THREAD

**Issue by thhalm** [graingert/slimerjs#22]
We use Artifactory to cache our dependent artifacts. In order to seamlessly integrate Slimerjs in our build process we need to be able to override the prefix of the download URL like it is possible for the phantom js npm package:

```javascript
function getDownloadUrl() {
  var cdnUrl = process.env.npm_config_phantomjs_cdnurl ||
      process.env.PHANTOMJS_CDNURL ||
      'https://bitbucket.org/ariya/phantomjs/downloads'
  var downloadUrl = cdnUrl + '/phantomjs-' + helper.version + '-'
  ...
```
https://github.com/Medium/phantomjs/blob/master/install.js

Thanks in advance.

**Comment by graingert** [comment]
If this feature is in upstream, I'd rather accept a pull request to merge upstream and make the Slimer customisations

**Comment by thhalm** [comment]
was duplicate of #16, fine for me to merge upstream
