### ISSUE TITLE
Npm install issue

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [graingert/slimerjs#24]
I'm getting an `Exit status 1` error when trying to run the command `npm install slimerjs`. Any way I can tell if this is a me (local environment) problem or if there is something going on with the npm package? Thanks!

**Comment by graingert** [comment]
Oddness do you get an error message? Otherwise can you repeat the error on a docket or vagrant config and post that here?

**Comment by Blackbaud-PatrickOFriel** [comment]
I'm going to go ahead and close this, the command was failing earlier this afternoon, but it's working fine now. I might have just had something wonky going on in my environment. Thanks for your quick response!
