### ISSUE TITLE
install.js issue

### ISSUE THREAD

**Issue by jmatc** [graingert/slimerjs#31]
I don't ever remember ever installing slimerjs.

npm ERR! slimerjs@0.9.6-1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slimerjs@0.9.6-1 install script.
npm ERR! This is most likely a problem with the slimerjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls slimerjs
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/jocalvin/.nvm/v0.10.40/bin/node" "/Users/jocalvin/.nvm/v0.10.40/bin/npm" "install" "-g" "slimerjs"
npm ERR! cwd /Users/jocalvin/.nvm/bin/node-v0.10.40-darwin-x64
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by AlexChesters** [comment]
We're having the same problem, looks like it's been fixed in [this commit](https://github.com/graingert/slimerjs/commit/1b3d8ffc2a5acef0fef4a5ec60516b2c3d769b70)

**Comment by graingert** [comment]
Fixed in #30

**Comment by AlexChesters** [comment]
@graingert when will this version be available on `npm`?

**Comment by graingert** [comment]
try 0.9.6-2

**Comment by AlexChesters** [comment]
awesome, cheers @graingert :+1: :shipit:
