### ISSUE TITLE
Can't install via npm?

### ISSUE THREAD

**Issue by Pomax** [graingert/slimerjs#34]
I tried the `npm install slimerjs` approach, but that generates the following error for me:
```
C:\Users\Mike\Documents\Git projects\projects\BezierInfo-2>npm install slimerjs --save-dev
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "slimerjs" "--save-dev"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\Mike\AppData\Roaming\npm-cache\slimerjs\0.9.5\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\Mike\AppData\Roaming\npm-cac
he\slimerjs\0.9.5\package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mike\Documents\Git projects\projects\BezierInfo-2\npm-debug.log
```
It looks like it's trying to grab a release version that doesn't exist?

**Comment by GFriedrich** [comment]
Happens for me too. The npm-debug.log shows that slimerjs first is resolved with version 0.9.5.
Later it downloads version 0.9.6. But then it tries to extract version 0.9.5 again. :-1:

**Comment by yunntan** [comment]
I was facing the same problem; Try downloading version 0.9.6, it worked fine for me :+1: 
`npm install slimerjs@0.9.6`

**Comment by GFriedrich** [comment]
Problem is: I can't, because I want to install a different package which uses this one as dependency and I can't change which version of slimerjs is downloaded as dependency.

**Comment by graingert** [comment]
`npm install slimerjs@0.9.6-2` is also fine for me. Is this a bug in NPM?

**Comment by graingert** [comment]
Ah this is a bug in NPM see: https://github.com/npm/npm/issues/10057

**Comment by graingert** [comment]
which package do you use? You should submit an issue upstream to pin their packages

**Comment by GFriedrich** [comment]
Ah, good finding ... I want to install the "karma-slimerjs-launcher" package.

**Comment by graingert** [comment]
@GFriedrich I've uploaded 0.906.1 this should fix your issues.
