### ISSUE TITLE
SlimerJS Edge not installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by geekdenz** [graingert/slimerjs#36]
The build system didn't work correctly on my machine (Ubuntu 14.04 LTS Linux).

I tracked down the problem and it comes down to https://download.slimerjs.org/nightlies/0.10.0pre/slimerjs-0.10.0pre-linux-x86_64.tar.bz2 giving a 404. To work around this problem, I had to clone this repository:
https://github.com/bitjson/slimerjs-edge
download SlimerJS from https://download.slimerjs.org/nightlies/0.10.0pre/slimerjs-0.10.0pre.zip
unzip the source like so
```unzip slimerjs-0.10.0pre.zip```
and tar the resulting files to /tmp/slimerjs-0.10.0pre-linux-x86_64.tar.bz2 like so:
```tar cfj /tmp/slimerjs-0.10.0pre-linux-x86_64.tar.bz2 slimerjs-0.10.0pre```

There are more steps necessary. You have to install SlimerJS in your system, but this would then detect the file being downloaded and install correctly. I believe it was 
```node ./install.js```
in the slimerjs-edge folder.

**Comment by graingert** [comment]
slimerjs-edge is not supported by this repo. https://github.com/bitjson/slimerjs-edge
