### ISSUE TITLE
Publish new version to npm?

### ISSUE THREAD

**Issue by pdehaan** [graingert/slimerjs#37]
I just installed SlimerJS from npm and it looks like the latest version is 0.906.1.
If I do something like this:

```js
var page = require('webpage').create();

console.log(page.settings.userAgent);
```

Then I get the following output:
```sh
$ npm run slimer

> phantomjs-test@1.0.0 preslimer /Users/pdehaan/dev/tmp/del/phantomjs-test
> slimerjs --version

Innophi SlimerJS 0.9.6, Copyright 2012-2015 Laurent Jouanneau & Innophi

> phantomjs-test@1.0.0 slimer /Users/pdehaan/dev/tmp/del/phantomjs-test
> slimerjs test.js

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:33.0) Gecko/20100101 SlimerJS/0.9.6
```

So it looks like I'm using "SlimerJS/0.9.6" and not [SlimerJS 0.10](https://slimerjs.org/download.html).

I installed locally using "npm install slimerjs -S" and my package.json looks roughly like this.

```json
{
  "name": "phantomjs-test",
  "version": "1.0.0",
  "scripts": {
    "preslimer": "slimerjs --version",
    "slimer": "slimerjs test.js",
    "prephantom": "phantomjs --version",
    "phantom": "phantomjs test.js"
  },
  "dependencies": {
    "phantomjs-prebuilt": "2.1.7",
    "slimerjs": "0.906.1"
  }
}
```

Not sure if there is a way to currently install slimerjs@0.10 via npm, or if I have to do it manually.

**Comment by graingert** [comment]
It does certainly look like that. Currently it's expected behaviour

**Comment by pdehaan** [comment]
Ah, so 0.10.x isn't in the stable branch yet?

Basically we're trying to use Slimer to do some validation (see https://github.com/mozilla/testpilot/issues/755#issuecomment-221084435) but we're getting Script Errors saying:

> [JavaScript Error: "ReferenceError: WeakSet is not defined"]

My guess is that the 0.9.6 version of Slimer has an old version of Firefox which doesn't have support for WeakSet.

**Comment by graingert** [comment]
@pdehaan I don't think this repo is appropriate for how slimerjs 0.10 works. (It's just a firefox wrapper now)

**Comment by meandavejustice** [comment]
@graingert I think @pdehaan is asking for this line to be updated https://github.com/graingert/slimerjs/blob/master/lib/slimerjs.js#L31

**Comment by graingert** [comment]
yeah that won't work because the downloads don't exist on slimerjs.org, slimerjs is just a bash wrapper around Firefox now. This code needs to be completely re-worked

**Comment by graingert** [comment]
0.10 will not be supported by this wrapper.

**Comment by meandavejustice** [comment]
Is this not the download you need? http://download.slimerjs.org/releases/0.10.0/slimerjs-0.10.0.zip

**Comment by graingert** [comment]
@meandavejustice please see https://github.com/laurentj/slimerjs/issues/489

**Comment by rmarx** [comment]
you can download the 0.10.0.zip and unzip where you want, then update the location.js file for the NPM plugin to point to that location. 

This kind of makes installing via the NPM plugin a bit useless (will even download and keep the older version), but if it's part of a bigger Node ecosystem (in my case, it was sitespeed.io) it works without other changes. 

A better NPM integration would be interesting though...
