### ISSUE TITLE
Consider including slimerjs binary

### ISSUE THREAD

**Issue by KevinGrandon** [graingert/slimerjs#40]
Now that slimerjs has started blocking various IPs from downloading its binary[1] I would suggest to bundle the slimerjs binary with this npm package if possible. That way everything you need can just come from a single source (npm) which is less prone to breakage.

[1] https://twitter.com/slimerjs/status/740123826969837568?lang=en

**Comment by benoitMariaux** [comment]
+1

**Comment by eventualbuddha** [comment]
While it'd be great to not have to think about such issues, I don't think it's feasible. Bundling 0.9.6 would make the npm package over 156 MB to include all the versions that might be needed. That's crazy. We have an option to download it from a specific (hopefully internal) CDN. We should use that option.

**Comment by graingert** [comment]
really people should be using >= 0.10.0 from now on.

Please upvote or create PRs to fix: https://github.com/laurentj/slimerjs/issues/489
