### ISSUE TITLE
Difference between doc version and release

### ISSUE THREAD

**Issue by ImpactSeo** [graingert/slimerjs#45]
Hi and thanks for your work !

Could you explain me why your docs refrer to 0.10.0 version and latest release is 0.9.6 ? it seems confusing to me and when I launch casper with some options like --ignore-ssl-errors=true it says me tis option is not available but docs says it is so ... is there a 0.10.0 release on github repo or should I install master branch ? Thanks for your lights !

**Comment by graingert** [comment]
0.10.0 will not be supported by this repo.

https://github.com/graingert/slimerjs/issues/37
