### ISSUE TITLE
use 0.10.1

### ISSUE THREAD

**Issue by yairEO** [graingert/slimerjs#51]
I see there's a new version `0.10.1` on slimerjs website, but on this repo it's still on `0.906.2` 

why?

**Comment by graingert** [comment]
https://github.com/graingert/slimerjs#0100

**Comment by graingert** [comment]
https://github.com/laurentj/slimerjs/issues/489

**Comment by yairEO** [comment]
There is not tag for that version :)
also, the latest version shown on NPM page is the `0.906.2` and that's what is installed as default

**Comment by graingert** [comment]
# https://github.com/graingert/slimerjs#0100

**Comment by yairEO** [comment]
haha NOW I get it (big font helps)
